
services:
  tabg:
    image: ghcr.io/kaindorf-games/tabg-server:main
    volumes:
      - ./config:/games/config
      - ./logs:/games/logs
    environment:
      - LEADERBOARD_URL=http://192.168.1.130:8001
      - LEADERBOARD_NAME=gametriathlon-vulkan-lan-24
      - GAME_NAME=TABG
      - LEADERBOARD_USER=game
      - LEADERBOARD_PASSWORD=1234
      - MAX_POINTS=60
      - WRITE_TO_LOGS=1
      - WRITE_TO_FILE=1
      - FEED_TO_MANAGER=0